

1. load all TMF tiles
2. one by one, iterate through and extract samples if

In [20]:
import os
import sys

import pandas as pd
import geopandas as gpd
import rasterio
import numpy as np

sys.path.append('../')

from utils import get_tiles_as_gdf

In [28]:
patch_rows, patch_cols = 33, 33 #based on how i extracted training samples

min_px_forest_loss = 5 #I can also try with less
target_years = [2021]

In [29]:

forestloss_dir = '../../Vancutsem_yearloss'
forestloss_tiles = get_tiles_as_gdf(forestloss_dir)

In [30]:
forestloss_tiles

,geometry,filename
0,"POLYGON ((-100.00000 20.00000, -100.00000 30.0...",../../Vancutsem_yearloss/tile_N30_W110.tif
1,"POLYGON ((-90.00000 20.00000, -90.00000 30.000...",../../Vancutsem_yearloss/tile_N30_W100.tif
2,"POLYGON ((-80.00000 20.00000, -80.00000 30.000...",../../Vancutsem_yearloss/tile_N30_W90.tif
3,"POLYGON ((-70.00000 20.00000, -70.00000 30.000...",../../Vancutsem_yearloss/tile_N30_W80.tif
4,"POLYGON ((80.00000 20.00000, 80.00000 30.00000...",../../Vancutsem_yearloss/tile_N30_E70.tif
...,...,...
81,"POLYGON ((160.00000 -30.00000, 160.00000 -20.0...",../../Vancutsem_yearloss/tile_S20_E150.tif
82,"POLYGON ((170.00000 -30.00000, 170.00000 -20.0...",../../Vancutsem_yearloss/tile_S20_E160.tif
83,"POLYGON ((-50.00000 -40.00000, -50.00000 -30.0...",../../Vancutsem_yearloss/tile_S30_W60.tif
84,"POLYGON ((150.00000 -40.00000, 150.00000 -30.0...",../../Vancutsem_yearloss/tile_S30_E140.tif
85,"POLYGON ((160.00000 -40.00000, 160.00000 -30.0...",../../Vancutsem_yearloss/tile_S30_E150.tif

In [31]:
target_years

[2021]

In [ ]:
patches_per_tile_min5pix = []

for idx, row in forestloss_tiles.iterrows():
    print(idx)
    with rasterio.open(row.filename) as source:
        data = source.read(1)
    if not np.any(data == target_years[0]):
        continue
    
    tile_patches = 0
    for i in range(0, data.shape[0], patch_rows):
        for j in range(0, data.shape[1], patch_cols):
            patch = data[i:i+patch_rows, j:j+patch_cols]

            forest_loss_mask = (np.isin(patch, target_years))

            # Check if there is enough forest loss
            if not forest_loss_mask.sum() >= min_px_forest_loss:
                continue
            tile_patches += 1
    
    patches_per_tile_min5pix.append(tile_patches)

In [39]:
forestloss_tiles['n_patches_min_5_px'] = patches_per_tile_min5pix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint16)

In [33]:
forestloss_tiles['n_patches_min_15_px'] = patches_per_tile

In [34]:
forestloss_tiles

,geometry,filename,n_patches_min_15_px
0,"POLYGON ((-100.00000 20.00000, -100.00000 30.0...",../../Vancutsem_yearloss/tile_N30_W110.tif,2572
1,"POLYGON ((-90.00000 20.00000, -90.00000 30.000...",../../Vancutsem_yearloss/tile_N30_W100.tif,3445
2,"POLYGON ((-80.00000 20.00000, -80.00000 30.000...",../../Vancutsem_yearloss/tile_N30_W90.tif,1043
3,"POLYGON ((-70.00000 20.00000, -70.00000 30.000...",../../Vancutsem_yearloss/tile_N30_W80.tif,1753
4,"POLYGON ((80.00000 20.00000, 80.00000 30.00000...",../../Vancutsem_yearloss/tile_N30_E70.tif,48
...,...,...,...
81,"POLYGON ((160.00000 -30.00000, 160.00000 -20.0...",../../Vancutsem_yearloss/tile_S20_E150.tif,8
82,"POLYGON ((170.00000 -30.00000, 170.00000 -20.0...",../../Vancutsem_yearloss/tile_S20_E160.tif,131
83,"POLYGON ((-50.00000 -40.00000, -50.00000 -30.0...",../../Vancutsem_yearloss/tile_S30_W60.tif,515
84,"POLYGON ((150.00000 -40.00000, 150.00000 -30.0...",../../Vancutsem_yearloss/tile_S30_E140.tif,0
85,"POLYGON ((160.00000 -40.00000, 160.00000 -30.0...",../../Vancutsem_yearloss/tile_S30_E150.tif,0

In [26]:
forestloss_tiles.n_patches.sum()

1248070

In [21]:
n_patches = 0

In [15]:
patch.shape

(33, 33)

In [17]:
patch.max()

0

In [22]:
n_patches

2572